---
- name: test
  gather_facts: false
  hosts: all  # Используем группу 'all' вместо 'webservers'
  vars:
    ansible_ssh_user: ubuntu
  become: yes

  pre_tasks:
    - name: Validating the ssh port is open
      wait_for:
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        port: 22
        delay: 5
        timeout: 300
        state: started
        search_regex: OpenSSH

  tasks:
    - name: Test connection
      ansible.builtin.ping:
